import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "hi" | "ur";

export interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Sidebar & Menus
    dashboard: "Dashboard",
    global_dashboard: "Global Dashboard",
    party_dashboard: "Party Dashboard",
    parties_management: "Parties Management",
    purchases: "Purchases",
    sales: "Sales",
    expenses: "Expenses",
    labour_manage: "Labour Manage",
    inventory: "Inventory",
    partners: "Partners",
    notifications: "Notifications",

    // Headers & Labels
    app_title: "RICE MILL ERP",
    global_admin_header: "Global Administrative Command",
    dashboard_summary: "Quick Overview & Metrics",
    recent_activities: "Recent Activities",
    weekly_trend: "Weekly Performance Trend",
    isolated: "Isolated",
    active: "Active",
    inactive: "Inactive",
    actions: "Actions",
    search_placeholder: "Search record...",
    settings: "Settings",
    sign_out: "Sign Out",

    // Dashboard Cards
    total_parties: "Total Parties",
    active_parties: "Active Parties",
    total_purchase: "Total Purchase",
    total_sales: "Total Sales",
    total_expenses: "Total Expenses",
    net_profit: "Net Profit",
    inventory_items: "Inventory Items",
    labour_count: "Labour Count",

    // Button actions
    provision_new_party: "Provision New Party",
    register_new_partner: "Register New Partner",
    cancel: "Cancel",
    save_changes: "Save Changes",
    register_partner: "Register Partner",
    provision_channel: "Provision Channel",
    edit: "Edit",
    delete: "Delete",

    // Form fields
    mill_name: "Mill Name",
    tenant_code: "Tenant Code",
    register_number: "Register Number",
    owner_name: "Owner Name",
    owner_mobile: "Owner Mobile",
    mill_email: "Mill Email",
    mill_contact: "Mill Contact",
    state: "State",
    city: "City",
    town_village: "Town / Village",
    subscription_billing: "Subscription Billing (Free Trial)",
    select_trial_duration: "Select Trial Duration",
    free_trial: "Free Trial",
    three_months: "3 Months Free Trial",
    six_months: "6 Months Free Trial",
    one_year: "1 Year Free Trial",

    // Partner labels
    full_name: "Full Name",
    email_address: "Email Address",
    mobile_whatsapp: "Mobile / WhatsApp Number",
    password: "Password",

    // Record fields
    item_name: "Item Name",
    quantity: "Quantity",
    unit: "Unit",
    price_per_unit: "Price Per Unit",
    supplier_name: "Supplier Name",
    buyer_name: "Buyer Name",
    date: "Date",
    add_purchase: "Record New Purchase",
    add_sale: "Record New Sale",
    category: "Category",
    amount: "Amount",
    description: "Description",
    add_expense: "Record New Expense",
    wage: "Daily Wage",
    present_days: "Present Days",
    unpaid_dues: "Unpaid Dues",
    contact: "Contact Number",
    add_labour: "Register New Labour",
    min_stock_alert: "Min Stock Alert",
    stock_quantity: "Stock Quantity",
    add_inventory: "Add Inventory Item",
    procured_paddy_materials: "Procured Paddy Materials",
    operational_cost_daily_wages: "Operational costs + daily wages",
    operations_snapshot: "Operations Snapshot",
    stocked_materials_byproducts: "Stocked materials & byproducts",
    active_labour_force: "Active Labour force",
    operators_loaders_checkers: "Operators, loaders & checkers",
    system_alert: "System Alert",
    system_alert_desc: "Paddy Raw Basmati (1121) is near minimal stock levels. Advise purchase manager to initiate farmer procurement.",
    recent_transactions: "Recent Transactions",
    latest_5_records: "Latest 5 records",
    shortcut_operations: "Shortcut Operations",
    shortcut_operations_desc: "Access dedicated panels for specific logging.",
    hello: "Hello",
    mill_party: "Mill Party",
    today: "Today",
    last_7_days: "Last 7 Days",
    last_30_days: "Last 30 Days",
    custom_all_time: "Custom (All-Time)",
    partner_access_view_only: "Partner Access (View-Only)",
    full_admin_controls_enabled: "Full Admin Controls Enabled",
    notifications_audit: "Notifications & Broadcasts Audit",
    notifications_audit_desc: "Historical ledger of changes made by the Admin and automated WhatsApp broadcast alerts dispatched to partners.",
    fetching_notifications: "Fetching notifications log...",
    failed_notifications: "Failed to load notifications log.",
    no_notifications: "No Notifications",
    no_notifications_desc: "Your notification box is currently empty.",
    mark_read: "Mark Read",
    wa_dispatch_status: "Simulated WhatsApp Dispatch Status",
    activity_sold: "Sold {quantity} bags of {itemName} for Rs.{amount}",
    activity_bought: "Bought {quantity} bags of {itemName} for Rs.{amount}",
    activity_paid: "Paid Rs.{amount} for {category}",
    purchases_desc: "Log and manage incoming paddy grains, packaging supplies, and stock intake.",
    sales_desc: "Track wholesale outgoing basmati shipments, processing byproducts, and revenue flow.",
    expenses_desc: "Log mill electricity bills, boiler maintenance costs, fuels, and general overhead.",
    labour_desc: "Register daily wage workers, verify active operators, track present days, and manage dues payouts.",
    inventory_desc: "Audit raw paddy reserves, finished bags, byproducts, and set automated min-stock threshold alerts.",
    partners_desc: "Register and manage multiple partners associated with this mill channel.",
    parties_desc: "Global administrative control panel to provision and manage distinct mill channels.",
    dashboard_desc: "Overview of all registered mill parties, tenant growth, and platform health.",
    vs_last_month: "vs last month",
    net_profit_formula: "Sales - Purchase - Expenses - Wages",
    designation: "Designation",
    total_wages: "Total Wages",
    download_report: "Download PDF Report",
  },
  hi: {
    // Sidebar & Menus
    dashboard: "डैशबोर्ड",
    global_dashboard: "ग्लोबल डैशबोर्ड",
    party_dashboard: "पार्टी डैशबोर्ड",
    parties_management: "पार्टी प्रबंधन",
    purchases: "खरीद विवरण",
    sales: "बिक्री विवरण",
    expenses: "खर्च विवरण",
    labour_manage: "श्रमिक प्रबंधन",
    inventory: "स्टॉक / इन्वेंटरी",
    partners: "साझेदार विवरण",
    notifications: "सूचनाएं",

    // Headers & Labels
    app_title: "राइस मिल ईआरपी",
    global_admin_header: "वैश्विक प्रशासनिक नियंत्रण",
    dashboard_summary: "त्वरित अवलोकन और मेट्रिक्स",
    recent_activities: "हाल की गतिविधियां",
    weekly_trend: "साप्ताहिक प्रदर्शन रुझान",
    isolated: "पृथक (सुरक्षित)",
    active: "सक्रिय",
    inactive: "निष्क्रिय",
    actions: "कार्रवाई",
    search_placeholder: "खोजें...",
    settings: "सेटिंग्स",
    sign_out: "लॉग आउट",

    // Dashboard Cards
    total_parties: "कुल पार्टियाँ",
    active_parties: "सक्रिय पार्टियाँ",
    total_purchase: "कुल खरीद",
    total_sales: "कुल बिक्री",
    total_expenses: "कुल खर्च",
    net_profit: "शुद्ध लाभ",
    inventory_items: "स्टॉक वस्तुएं",
    labour_count: "कुल श्रमिक",

    // Button actions
    provision_new_party: "नई पार्टी जोड़ें",
    register_new_partner: "नया साझेदार पंजीकृत करें",
    cancel: "रद्द करें",
    save_changes: "परिवर्तन सहेजें",
    register_partner: "साझेदार जोड़ें",
    provision_channel: "चैनल चालू करें",
    edit: "संपादित करें",
    delete: "हटाएं",

    // Form fields
    mill_name: "मिल का नाम",
    tenant_code: "टैनेंट कोड",
    register_number: "पंजीकरण संख्या",
    owner_name: "मालिक का नाम",
    owner_mobile: "मालिक का मोबाइल नंबर",
    mill_email: "मिल का ईमेल",
    mill_contact: "मिल का संपर्क",
    state: "राज्य",
    city: "शहर",
    town_village: "कस्बा / गाँव",
    subscription_billing: "सदस्यता बिलिंग (निःशुल्क परीक्षण)",
    select_trial_duration: "परीक्षण अवधि चुनें",
    free_trial: "निःशुल्क परीक्षण",
    three_months: "3 महीने का निःशुल्क परीक्षण",
    six_months: "6 महीने का निःशुल्क परीक्षण",
    one_year: "1 वर्ष का निःशुल्क परीक्षण",

    // Partner labels
    full_name: "पूरा नाम",
    email_address: "ईमेल पता",
    mobile_whatsapp: "मोबाइल / व्हाट्सएप नंबर",
    password: "पासवर्ड",

    // Record fields
    item_name: "वस्तु का नाम",
    quantity: "मात्रा",
    unit: "इकाई",
    price_per_unit: "प्रति इकाई मूल्य",
    supplier_name: "आपूर्तिकर्ता का नाम",
    buyer_name: "क्रेता का नाम",
    date: "दिनांक",
    add_purchase: "नई खरीद दर्ज करें",
    add_sale: "नई बिक्री दर्ज करें",
    category: "श्रेणी",
    amount: "राशि",
    description: "विवरण",
    add_expense: "नया खर्च दर्ज करें",
    wage: "दैनिक मजदूरी",
    present_days: "उपस्थित दिन",
    unpaid_dues: "बकाया राशि",
    contact: "संपर्क नंबर",
    add_labour: "नया श्रमिक पंजीकृत करें",
    min_stock_alert: "न्यूनतम स्टॉक चेतावनी",
    stock_quantity: "स्टॉक मात्रा",
    add_inventory: "स्टॉक वस्तु जोड़ें",
    procured_paddy_materials: "खरीदी गई धान सामग्री",
    operational_cost_daily_wages: "परिचालन लागत + दैनिक मजदूरी",
    operations_snapshot: "संचालन स्नैपशॉट",
    stocked_materials_byproducts: "स्टॉक की गई सामग्री और उप-उत्पाद",
    active_labour_force: "सक्रिय श्रमिक बल",
    operators_loaders_checkers: "ऑपरेटर, लोडर और चेकर",
    system_alert: "सिस्टम चेतावनी",
    system_alert_desc: "धान कच्चा बासमती (1121) न्यूनतम स्टॉक स्तर के करीब है। खरीद प्रबंधक को किसान खरीद शुरू करने की सलाह दें।",
    recent_transactions: "हाल के लेन-देन",
    latest_5_records: "नवीनतम 5 रिकॉर्ड",
    shortcut_operations: "शॉर्टकट संचालन",
    shortcut_operations_desc: "विशिष्ट लॉगिंग के लिए समर्पित पैनलों तक पहुंचें।",
    hello: "नमस्ते",
    mill_party: "मिल पार्टी",
    today: "आज",
    last_7_days: "पिछले 7 दिन",
    last_30_days: "पिछले 30 दिन",
    custom_all_time: "कस्टम (कुल समय)",
    partner_access_view_only: "साझेदार पहुंच (केवल देखने के लिए)",
    full_admin_controls_enabled: "पूर्ण व्यवस्थापक नियंत्रण सक्षम",
    notifications_audit: "सूचनाएं और प्रसारण ऑडिट",
    notifications_audit_desc: "प्रशासक द्वारा किए गए परिवर्तनों का ऐतिहासिक खाता और भागीदारों को भेजे गए स्वचालित व्हाट्सएप प्रसारण अलर्ट।",
    fetching_notifications: "सूचनाएं लॉग प्राप्त किया जा रहा है...",
    failed_notifications: "सूचनाएं लॉग लोड करने में विफल।",
    no_notifications: "कोई सूचना नहीं",
    no_notifications_desc: "आपका सूचना बॉक्स वर्तमान में खाली है।",
    mark_read: "पढ़ा हुआ चिह्नित करें",
    wa_dispatch_status: "सिम्युलेटेड व्हाट्सएप प्रेषण स्थिति",
    activity_sold: "{itemName} के {quantity} बैग रुपये {amount} में बेचे गए",
    activity_bought: "{itemName} के {quantity} बैग रुपये {amount} में खरीदे गए",
    activity_paid: "{category} के लिए रुपये {amount} का भुगतान किया गया",
    purchases_desc: "आने वाले धान के अनाज, पैकेजिंग आपूर्ति और स्टॉक प्राप्ति का प्रबंधन करें।",
    sales_desc: "थोक बासमती लदान, उप-उत्पादों के प्रसंस्करण और राजस्व प्रवाह को ट्रैक करें।",
    expenses_desc: "मिल बिजली बिल, बॉयलर रखरखाव लागत, ईंधन और सामान्य ओवरहेड दर्ज करें।",
    labour_desc: "दैनिक वेतन भोगी श्रमिकों को पंजीकृत करें, सक्रिय ऑपरेटरों को सत्यापित करें, उपस्थिति को ट्रैक करें और बकाया का प्रबंधन करें।",
    inventory_desc: "कच्चे धान के स्टॉक, तैयार बैग, उप-उत्पादों का ऑडिट करें और स्वचालित न्यूनतम स्टॉक अलर्ट सेट करें।",
    partners_desc: "इस मिल चैनल से जुड़े कई साझेदारों को पंजीकृत और प्रबंधित करें।",
    parties_desc: "विशिष्ट मिल चैनलों को प्रावधान और प्रबंधित करने के लिए वैश्विक प्रशासनिक नियंत्रण कक्ष।",
    dashboard_desc: "सभी पंजीकृत मिल दलों, टैनेंट वृद्धि और प्लेटफ़ॉर्म स्वास्थ्य का अवलोकन।",
    vs_last_month: "पिछले महीने की तुलना में",
    net_profit_formula: "बिक्री - खरीद - खर्च - मजदूरी",
    designation: "पद",
    total_wages: "कुल मजदूरी",
    download_report: "पीडीएफ रिपोर्ट डाउनलोड करें",
  },
  ur: {
    // Sidebar & Menus
    dashboard: "ڈیش بورڈ",
    global_dashboard: "عالمی ڈیش بورڈ",
    party_dashboard: "پارٹی ڈیش بورڈ",
    parties_management: "پارٹیوں کا انتظام",
    purchases: "خریداری",
    sales: "فروخت",
    expenses: "اخراجات",
    labour_manage: "مزدوروں کا انتظام",
    inventory: "انوینٹری",
    partners: "شراکت دار",
    notifications: "اطلاعات",

    // Headers & Labels
    app_title: "رائس مل ای آر پی",
    global_admin_header: "عالمی انتظامی کنٹرول",
    dashboard_summary: "فوری جائزہ اور میٹرکس",
    recent_activities: "حالیہ سرگرمیاں",
    weekly_trend: "ہفتہ وار کارکردگی",
    isolated: "الگ تھلگ",
    active: "فعال",
    inactive: "غیر فعال",
    actions: "اقدامات",
    search_placeholder: "تلاش کریں...",
    settings: "ترتیبات",
    sign_out: "لاگ آؤٹ",

    // Dashboard Cards
    total_parties: "کل پارٹیاں",
    active_parties: "فعال پارٹیاں",
    total_purchase: "کل خریداری",
    total_sales: "کل فروخت",
    total_expenses: "کل اخراجات",
    net_profit: "کل منافع",
    inventory_items: "کل اسٹاک",
    labour_count: "مزدوروں کی تعداد",

    // Button actions
    provision_new_party: "نئی پارٹی شامل کریں",
    register_new_partner: "نیا شراکت دار رجسٹر کریں",
    cancel: "منسوخ کریں",
    save_changes: "تبدیلیاں محفوظ کریں",
    register_partner: "شراکت دار رجسٹر کریں",
    provision_channel: "چینل شروع کریں",
    edit: "تبدیل کریں",
    delete: "حذف کریں",

    // Form fields
    mill_name: "مل کا نام",
    tenant_code: "ٹیننٹ کوڈ",
    register_number: "رجسٹریشن نمبر",
    owner_name: "مالک کا نام",
    owner_mobile: "مالک کا موبائل نمبر",
    mill_email: "مل کا ای میل",
    mill_contact: "مل کا رابطہ نمبر",
    state: "صوبہ / ریاست",
    city: "شہر",
    town_village: "قصبہ / گاؤں",
    subscription_billing: "سبسکرپشن بلنگ (مفت ٹرائل)",
    select_trial_duration: "ٹرائل کی مدت منتخب کریں",
    free_trial: "مفت ٹرائل",
    three_months: "3 ماہ کا مفت ٹرائل",
    six_months: "6 ماہ کا مفت ٹرائل",
    one_year: "1 سال کا مفت ٹرائل",

    // Partner labels
    full_name: "پورا نام",
    email_address: "ای میل پتہ",
    mobile_whatsapp: "موبائل / واٹس ایپ نمبر",
    password: "پاس ورڈ",

    // Record fields
    item_name: "آئٹم کا نام",
    quantity: "مقدار",
    unit: "یونٹ",
    price_per_unit: "فی یونٹ قیمت",
    supplier_name: "سپلائر کا نام",
    buyer_name: "خریدار کا نام",
    date: "تاریخ",
    add_purchase: "نئی خریداری درج کریں",
    add_sale: "نئی فروخت درج کریں",
    category: "زمرہ",
    amount: "رقم",
    description: "تفصیل",
    add_expense: "نیا خرچہ درج کریں",
    wage: "روزانہ اجرت",
    present_days: "حاضری کے دن",
    unpaid_dues: "بقایا جات",
    contact: "رابطہ نمبر",
    add_labour: "نیا مزدور رجسٹر کریں",
    min_stock_alert: "کم از کم اسٹاک الرٹ",
    stock_quantity: "اسٹاک کی مقدار",
    add_inventory: "اسٹاک آئٹم شامل کریں",
    procured_paddy_materials: "خریداری شدہ دھان کا مواد",
    operational_cost_daily_wages: "آپریشنل اخراجات + روزانہ اجرت",
    operations_snapshot: "آپریشنز کا خلاصہ",
    stocked_materials_byproducts: "ذخیرہ شدہ مواد اور ضمنی مصنوعات",
    active_labour_force: "فعال مزدور قوت",
    operators_loaders_checkers: "آپریٹرز، لوڈرز اور چیکرز",
    system_alert: "سستم الرٹ",
    system_alert_desc: "دھان کچی باسمتی (1121) کم از کم اسٹاک کی سطح کے قریب ہے۔ پرچیز مینیجر کو کسانوں سے خریداری شروع کرنے کا مشورہ دیں۔",
    recent_transactions: "حالیہ لین دین",
    latest_5_records: "تازہ ترین 5 ریکارڈز",
    shortcut_operations: "شارٹ کٹ آپریشنز",
    shortcut_operations_desc: "مخصوص لاگنگ کے لیے وقف پینلز تک رسائی حاصل کریں۔",
    hello: "ہیلو",
    mill_party: "مل پارٹی",
    today: "آج",
    last_7_days: "گزشتہ 7 دن",
    last_30_days: "گزشتہ 30 دن",
    custom_all_time: "اپنی مرضی کے مطابق (کل وقت)",
    partner_access_view_only: "شراکت دار کی رسائی (صرف دیکھنے کے لیے)",
    full_admin_controls_enabled: "مکمل ایڈمن کنٹرول فعال",
    notifications_audit: "اطلاعات اور نشریات کا آڈٹ",
    notifications_audit_desc: "ایڈمن کی طرف سے کی گئی تبدیلیوں کا تاریخی کھاتہ اور شراکت داروں کو بھیجے گئے خودکار واٹس ایپ براڈکاسٹ الرٹس۔",
    fetching_notifications: "اطلاعات لاگ حاصل کیا جا رہا ہے...",
    failed_notifications: "اطلاعات لاگ لوڈ کرنے میں ناکام۔",
    no_notifications: "کوئی اطلاع نہیں",
    no_notifications_desc: "آپ کا نوٹیفیکیشن باکس فی الحال خالی ہے۔",
    mark_read: "پڑھا ہوا نشان زد کریں",
    wa_dispatch_status: "مصنوعی واٹس ایپ بھیجنے کی حیثیت",
    activity_sold: "{itemName} کے {quantity} بیگ روپے {amount} میں فروخت ہوئے",
    activity_bought: "{itemName} کے {quantity} بیگ روپے {amount} میں خریدے گئے",
    activity_paid: "{category} کے لیے روپے {amount} ادا کیے گئے",
    purchases_desc: "دھان کے اناج، پیکیجنگ سپلائیز، اور اسٹاک انٹیک کا انتظام کریں۔",
    sales_desc: "تھوک باسمتی ترسیل، بائی پروڈکٹس کی پروسیسنگ اور آمدنی کے بہاؤ کو ٹریک کریں۔",
    expenses_desc: "مل کے بجلی کے بل، بوائلر کی دیکھ بھال کے اخراجات، ایندھن اور عام اوور ہیڈ لاگ کریں۔",
    labour_desc: "روزانہ اجرت والے مزدوروں کو رجسٹر کریں، فعال آپریٹرز کی تصدیق کریں، حاضری کو ٹریک کریں اور بقایا جات کا انتظام کریں۔",
    inventory_desc: "کچے دھان کے ذخائر، تیار شدہ بیگز، بائی پروڈکٹس کا آڈٹ کریں اور خودکار کم از کم اسٹاک الرٹس مرتب کریں۔",
    partners_desc: "اس مل چینل سے وابستہ متعدد شراکت داروں کو رجسٹر اور منظم کریں۔",
    parties_desc: "مختلف مل چینل کے انتظام کے لیے عالمی انتظامی کنٹرول پینل۔",
    dashboard_desc: "تمام رجسٹرڈ مل پارٹیوں، ٹیننٹ کی ترقی، اور پلیٹ فارم کی صحت کا جائزہ۔",
    vs_last_month: "پچھلے مہینے کے مقابلے",
    net_profit_formula: "فروخت - خریداری - اخراجات - مزدور",
    designation: "عہدہ",
    total_wages: "کل اجرت",
    download_report: "پی ڈی ایف رپورٹ ڈاؤن لوڈ کریں",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem("mill_locale") as Language) || "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("mill_locale", lang);
  };

  useEffect(() => {
    document.documentElement.dir = language === "ur" ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations["en"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
