export const PATHS = {
  ROOT: "/",
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  PURCHASE: "/purchase",
  SALES: "/sales",
  EXPENSES: "/expenses",
  INVENTORY: "/inventory",
  LABOUR: "/labour",
  NOTIFICATIONS: "/notifications",
  PARTY: "/party",
  PARTNERS: "/partners",
  ANALYTICS: "/analytics",
  PROFILE: "/profile",
  NOT_FOUND: "*",
} as const;